### ISSUE TITLE
Provide a "starter pack" of repos

### ISSUE THREAD

**Issue by gadomski** [developmentseed/ds-news#31]
I currently have:

- developmentseed/ds-business
- developmentseed/labs
- developmentseed/now
- developmentseed/operations

Obv each person will be different, but might be nice to something up on first load.

**Comment by alukach** [comment]
Closed by [e3b91df](https://github.com/developmentseed/ds-news/commit/e3b91dfea266f88c32d41a3b314de5fde3943b70)
